routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $threads=\App\Thread::paginate(15);
    return view('welcome',compact('threads'));
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/thread','ThreadController');

app/Thread.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
    protected $guarded=[];

    public function user(){
        $this->belongsTo(User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function threads(){
        return $this->hasMany(Thread::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ThreadController.php
<?php

namespace App\Http\Controllers;

use App\Thread;
use Illuminate\Http\Request;
use Session;

class ThreadController extends Controller
{
    function __construct()
    {
        $this->middleware('auth')->except('index');
    }

    public function index()
    {
        $threads=Thread::paginate(15);

        return view('thread.index',compact('threads'));
    }


    public function create()
    {
      return view('thread.create');
    }


    public function store(Request $request)
    {
        $this->validate($request,[
            'subject'=>'required|min:5',
            'type'=>'required',
            'thread'=>'required|min:20'
            ]);
        auth()->user()->threads()->create($request->all());
       // Thread::create($request->all());//I so ova metoda mozi da zacuvuvas
        Session::flash('success','Created with sucess');
        return redirect()->back();
    }

    public function show(Thread $thread)
    {
        return view('thread.single',compact('thread'));
    }


    public function edit(Thread $thread)
    {
        if(auth()->user()->id !== $thread->user_id)
        {
            return abort('403');
        }
        return view('thread.edit',compact('thread'));
    }


    public function update(Request $request,Thread $thread)
    {
        if(auth()->user()->id !== $thread->user_id)
        {
            return abort('403');
        }
        $this->validate($request,[
            'subject'=>'required|min:5',
            'type'=>'required',
            'thread'=>'required|min:20'
        ]);

        $thread->update($request->all());

        Session::flash('success','Edit with sucess');
        return redirect()->route('thread.show',$thread->id);
    }

    public function destroy(Thread $thread)
    {
        if(auth()->user()->id !== $thread->user_id)
        {
            return abort('403');
        }
        $thread->delete();
        Session::flash('success','Delete with sucess');
        return redirect()->route('thread.index');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/front.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Petar Forum</title>

    <link href="{{asset('add/bootstrap.min.css')}}" rel="stylesheet"/>
    <link href="{{asset('css/main.css')}}" rel="stylesheet"/>

</head>
<body>
@include('layouts.partials.nav')

@yield('banner')

<div class="container">

    <div class="row">
        @section('category')
            @include('layouts.partials.categories')
        @show
        <div class="col-md-9">
            <div class="row content-heading">
               <h4>@yield('heading')</h4>
            </div>
            <div class="content-wrap well">
                @yield('content')
            </div>
        </div>
    </div>
</div>
<script
    src="https://code.jquery.com/jquery-3.1.0.js"
    integrity="sha256-slogkvB1K3VOkzAI8QITxV3VzpOnkeNVsKvtkYLMjfk="
    crossorigin="anonymous"></script>

</body>
</html>

resources/views/layouts/partials/categories.blade.php
<div class="col-md-3">
    <h4>Category</h4>
    <ul class="list-group">
        <a href="{{route('thread.index')}}" class="list-group-item">
            <span class="badge">2</span>
            All Threads</a>

        <a href="#" class="list-group-item">
            <span class="badge">2</span>
            PHP
        </a>

        <a href="#" class="list-group-item">
            <span class="badge">3</span>
            Pyton
        </a>
    </ul>
</div>

resources/views/layouts/partials/error.blade.php
@if (count($errors)>0)
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/layouts/partials/nav.blade.php
<nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#app-navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Left Side Of Navbar -->
            <ul class="nav navbar-nav">
                &nbsp;
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->
                @if (Auth::guest())
                    <li><a href="{{ route('login') }}">Login</a></li>
                    <li><a href="{{ route('register') }}">Register</a></li>
                @else
                    {{--notification--}}
                  {{-- <notification :userid="{{auth()->id()}}" :unreads="{{auth()->user()->unreadNotifications}}"></notification>--}}

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu" role="menu">
                            <li>
                                <a href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    Logout
                                </a>

                               {{-- <a href="{{ route('user_profile',auth()->user()) }}">
                                    My Profile
                                </a>--}}

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                @endif
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/partials/success.blade.php
@if(session('success'))
    <div class="alert alert-success">
        {{session ('success')}}
    </div>
@endif

resources/views/main.blade.php
@extends('layouts.front')
@section('content')

    <div class="jumbotron">
        <div class="container">
            <h1>Forum Petar Join</h1>
            <p>Ask questions and Help Others</p>

        </div>
    </div>
    @endsection

resources/views/thread/create.blade.php
@extends('layouts.front')

@section('heading',"Create Thread")

@section('content')

   @include('layouts.partials.error')

   @include('layouts.partials.success')


    <div class="well">
        <form class="form-vertical" action="{{route('thread.store')}}" method="Post" role="form"
              id="create-thread-form">
            {{csrf_field()}}

            <div class="form-group">
                <label for="subject">Subject</label>
                <input type="text" class="form-control" name="subject" placeholder="Input" value="{{old('subject')}}">
            </div>

            <div class="form-group">
                <label for="subject">Type</label>
                <input type="text" class="form-control" name="type" placeholder="Input" value="{{old('type')}}">
            </div>

            <div class="form-group">
                <label for="subject">Thread</label>
                <textarea type="text" class="form-control" name="thread" placeholder="Input" value="{{old('thread')}}">
                </textarea>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/thread/edit.blade.php
@extends('layouts.front')

@section('heading',"Create Thread")

@section('content')

   @include('layouts.partials.error')

   @include('layouts.partials.success')


    <div class="well">
        <form class="form-vertical" action="{{route('thread.update',$thread->id)}}" method="Post" role="form"
              id="create-thread-form">
            {{csrf_field()}}
            {{method_field('put')}}

            <div class="form-group">
                <label for="subject">Subject</label>
                <input type="text" class="form-control" name="subject" placeholder="Input" value="{{$thread->subject}}">
            </div>

            <div class="form-group">
                <label for="subject">Type</label>
                <input type="text" class="form-control" name="type" placeholder="Input" value="{{$thread->type}}">
            </div>

            <div class="form-group">
                <label for="subject">Thread</label>
                <textarea type="text" class="form-control" name="thread" placeholder="Input" value="{{$thread->thread}}">
                    {{$thread->thread}}
                </textarea>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/thread/index.blade.php
@extends('layouts.front')
@section('heading')
    <a class="btn btn-primary pull-right" href="{{route('thread.create')}}">Create Threads</a>
@endsection
@section('content')


    @include('thread.partials.thread-list')
@endsection

resources/views/thread/partials/thread-list.blade.php
<div class="list-group">
    @forelse($threads as $thread)
        <a href="{{route('thread.show',$thread->id)}}" class="list-group-item">
            <h4 class="list-group-item-heading">{{$thread->subject}}</h4>
            <p class="list-group-item-text">{{$thread->thread,100}}</p>
        </a>
    @empty
        <h5>No threads</h5>
    @endforelse
</div>

resources/views/thread/single.blade.php
@extends('layouts.front')

@section('content')

    <h4>{{$thread->subject}}</h4>

    <div class="thread-details">
        {{$thread->thread}}
    </div>

    @if(auth()->user()->id==$thread->user_id)

    <div class="actions">

        <a href="{{route('thread.edit',$thread->id)}}" class="btn btn-info btn-xs">Edit</a>

        <form action="{{route('thread.destroy',$thread->id)}}" method="Post" class="inline-it">
            {{csrf_field()}}
            {{method_field('DELETE')}}
            <input class="btn btn-xs btn-danger" type="submit" value="Delete">
        </form>
    </div>

    @endif


    @endsection